# Data Analysis in Python

> Data analysis is a process of inspecting, cleaning, transforming, and modeling data with the goal of discovering useful information, suggesting conclusions, and supporting decision-making.

Since python has no built-in support for arrays, the main library most data analysis packages are built on is [NumPy](http://www.numpy.org/). This offers the necessary data structures and operations required by most high level libraries. These libraries form a whole ecosystem which makes python one of the most complete languages for data analysis.

![](https://image.slidesharecdn.com/introductiontonumpy-130416133754-phpapp02/95/introduction-to-numpy-pydata-sv-2013-5-638.jpg?cb=1367252805)


## Numpy

> Python by itself doesn't have any built in data types for arrays or matrices. Any direct (matrix multiplication) or indirect (image manipulation) operations that require arrays are done with the numpy package.

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Numpy is one of the most commonly used and best supported libraries in python and is the basis of all numerical tools in python (most tools that we'll address from now on require it). 

Numpy is similar to matlab, as it is a fairly low level tool (many packages however - like pandas - feature higher level tools and are built on top of numpy).

### Arrays

Arrays are the most common data types in data science. A numpy array is a grid of values, all of the **same type**, and is **indexed by a tuple of nonnegative integers**.

Contrary to lists, arrays have a fixed size, which needs to be set during the creation of the array. This allows these structures to be much faster and memory-efficient compared to other python data structures.

An array has two main attributes:

- Its `dtype`, indicating the data type of **all elements** in the array.
- Its `shape`, which is a tuple showing the size (or length) of each dimension.

In mathematical terms:

- A 0D array, i.e. a number, is called a **scalar**.
- A 1D array is called a **vector**.
- A 2D array is called a **matrix**.
- A 3D array is called a **tensor**.

#### 1D Arrays

A one-dimensional array can be thought of as a list that has a predefined size (i.e. length) and can contain only elements of a single data type. 

Let's dive right in. We'll first define the following array in numpy:

$$ A =\left( \begin{array}{ccc}
1 & 2 & 3\end{array} \right) $$

In [1]:
from __future__ import print_function  # for python 2-3 compatibility
import numpy as np  # because we use numpy often, its more convenient to refer to it as np

A = np.array([1, 2, 3])  # this is how we define and initialize a known array

But, what **type** of an object is *A*?

In [2]:
print(type(A))

<class 'numpy.ndarray'>


`ndarray` stands for **N-dimensional array**. This is a generalized array that can have any number of dimensions and is the numpy's main data structure. We'll see more further down.

How can I access a **single element** in *A*?

In [3]:
print(A[0], A[1], A[2])

1 2 3


Indexing works like it did with lists. As in most data types in python, the indexing in numpy arrays starts from 0.

We said before that an array must contain elements of the same type.  

What is the **data type of the elements** in *A*?

In [4]:
print(type(A[0]))

<class 'numpy.int32'>


They're not regular integers, but a custom numpy 32-bit integer data type. We could also see this from a built in array variable.

In [5]:
print(A.dtype)

int32


Numpy supports a lot of different **data types**. Integers and Unsigned Integers (8, 16, 32, 64 bit), float (half - 16, single - 32 and double precision - 64), complex numbers (16, 32 and 64 bit) and others.

Now that we got that out of the way, how can we **change an element** in *A*?

In [6]:
A[0] = 2.9; A[1] = 5; A[2] = 7.1
print(A)

[2 5 7]


Note that because `A` is an array of ints, it cast the values we assigned to it as ints (rather than changing its data type to suit the values)

Slicing works like lists too.

In [7]:
print(A[:2])   # print the first two elements
print(A[-2:])  # print the last two elements

[2 5]
[5 7]


#### 2D Arrays

Two dimensional arrays are essentially matrices, they are the most common form of arrays we will use. We usually refer to the first dimension as *rows* and the second as *columns*. Dimensions are referred to as **axes** in numpy.

Let's create the array:
$$ B = \left( \begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \end{array} \right) $$

In [8]:
B = np.array([[1, 2, 3], [4, 5, 6]])  # we can initialize arrays with known values with a list of lists
print(B)

[[1 2 3]
 [4 5 6]]


The initialization is done through a list for the rows, containing lists of values for the columns.

Now say we want to retrieve the bottom right element (i.e. 6). The second row's index is 1 while the third column's index is 2.

In [9]:
print(B[1,2])

6


We just separate the two indices with a comma.

Slicing works on each dimension separately.

In [10]:
print(B[-1, ::2])  # print the last element from the odd columns

[4 6]


#### N-D Arrays

As N grows larger, these Arrays become increasingly more difficult to visualize and comprehend. However in numpy a 100D array is as complicated as a 3D one. This helps us a lot.

In [11]:
C = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17]]])  # list of list of lists
print(C)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


Indexing an element in an n-dimensional array isn't that hard.

Suppose that the:

- **i** is the index of the element's 1st dimension (axis=0).
- **j** is the index of the element's 2nd dimension (axis=1).
- **k** is the index of the element's 3rd dimension (axis=2).
- **l** is the index of the element's 4th dimension (axis=3).
- **m** is the index of the element's 5th dimension (axis=4).  
...

The element with the above indices in array `Arr` is:
```python
element = Arr[i, j, k, l, m, ...]
```

As an example, the element *13* in array *C*:
- **i** is 3.
- **j** is 1.
- **k** is 2.

In [12]:
print(C[2, 0, 1])

13


#### Slicing 

Slicing works separately for each axis.

If we want the middle sub-array of *C*:
$$ slc = \left( \begin{array}{ccc}
6 & 7 & 8 \\
9 & 10 & 11 \end{array} \right) $$

In [13]:
slc = C[1,:,:]  # we want the index 1 of the 1st axis and all the values from the rest
# this can also be written as C[1, ...]
print(slc)

[[ 6  7  8]
 [ 9 10 11]]


Likewise if we wanted just the right columns of *C*:
$$slc = \left( \begin{array}{ccc}
2  \\
5  \\
8  \\
11  \\
14  \\
17  \end{array} \right) $$

In [14]:
slc = C[:,:,2]
# or equivalently C[..., 2]
print(slc)

[[ 2  5]
 [ 8 11]
 [14 17]]


In order to turn `slc` into the format we wanted we must reshape it.

In [15]:
slc = slc.reshape((slc.size,1))
print(slc)
print(slc.shape)

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
(6, 1)


More on that later though.

Lastly, if we want the whole array as a slice:

In [16]:
slc = C[:]       # slice containing C as a whole
slc2 = C[:,:,:]  # same thing
slc3 = C[...]    # same
print(slc)
print(np.array_equal(C, slc), np.array_equal(slc, slc2), np.array_equal(slc2, slc3))
# check if C == slc, slc == slc2 and if slc2 == slc3 

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
True True True


#### Indexing arbitrary elements

By passing a list of indices, we can get a slice of any arbitrary positions we want!

In [27]:
print(A[[0, 2]])         # get elements in the positions 0 and 2 of array A
print(B[:, [0, 2]])      # get a slice of B with all the rows and columns in the positions 0 and 2
print(C[[0, 2], 0, :2])  # etc...

[2 7]


### Built-in Functions

There are also a lot of built-in functions in numpy arrays. The most important ones are the following

#### Array Information: 

- `A.dtype` returns the type of the elements in *A*.
- `A.shape` returns the shape of *A*, i.e. a tuple containing the size of its dimensions.
- `A.ndim` returns the rank of *A*, i.e. the number of its dimensions.
- `A.size` returns the number of elements in *A*, i.e. the product of the values in `A.shape`.
- `A.nbytes` returns the total bytes consumed by the elements of the array, i.e. (bytes in `A.dtype`) `* A.size / 8` .

#### Array Conversions:

- `A.tolist()` returns the array as a (possibly nested) list.
- `A.tofile()` writes *A* to a file as text or binary (default).
- `A.dump(file)` dumps a pickle of *A* to the specified *file*.
- `A.astype(dtype)` returns the copy of the array, cast to a specified type.
- `A.copy()` returns a copy of the *A*.

#### Shape Manipulation:

- `A.traspose` or `A.T` returns transposed *A*.
- `A.reshape(shape)` changes the shape of *A* to *shape*.
- `A.swapaxes(axis1, axis2)` returns a view of the array with axis1 and axis2 interchanged.
- `A.flatten()` returns a copy of the array collapsed into one dimension.
- `A.repeat(n)` repeats elements of an array *n* times. e.g. $ A =\left( \begin{array}{ccc}
1 & 2 & 3\end{array} \right) $ for $n=2$ becomes $ A =\left( \begin{array}{ccc}
1 & 1 & 2 & 2 & 3 & 3\end{array} \right) $

#### Item Manipulation:

- `A.sort()` sorts *A*, in-place.
- `A.argsort()` returns the indices that would sort *A*.
- `A.nonzero()`	returns the indices of the elements that are non-zero.

#### Calculations:

- `A.max()` returns the largest element in *A*.
- `A.min()` returns the smallest element in *A*.
- `A.sum()` returns the sum of the elements in *A*.
- `A.mean()` returns the mean of the elements in *A*.
- `A.var()` returns the variation of the elements in *A*.
- `A.std()` returns the standard deviation of the elements in *A*.
- `A.prod()` returns the product of the elements in *A*.
- `A.all()` returns True if all elements in *A* are True.
- `A.any()` returns True if any of the elements in *A* are True.

In [17]:
print('There are', C.size, 'elements in C.')
print('The shape of C is', C.shape)
print('The rank of C is', C.ndim)
print('\n')

print('Original Array:\n', C)
print('\n')
print('List equivalent:\n', C.tolist())
print('\n')

print('Transposed:\n', C.T)
print('\n')

print('max =', C.max())
print('min =', C.min())
print('sum =', C.sum())
print('mean =', C.mean())
print('sum / size = ', C.sum() / float(C.size))

There are 18 elements in C.
The shape of C is (3, 2, 3)
The rank of C is 3


Original Array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


List equivalent:
 [[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17]]]


Transposed:
 [[[ 0  6 12]
  [ 3  9 15]]

 [[ 1  7 13]
  [ 4 10 16]]

 [[ 2  8 14]
  [ 5 11 17]]]


max = 17
min = 0
sum = 153
mean = 8.5
sum / size =  8.5


### Array Creation

There are a lot of ways to create arrays. The basic way we saw up till now (which creates and populates the array) serves only for small arrays. What we tend to do in practice, is to create an array, either empty or containing placeholder values. Then we populate that array through iteration.

In [18]:
shp = (256, 256, 3)           # The shape we want our array to have
E = np.empty(shp, dtype='f')  # We create an empty array with the predefined shape and data type
print(E[0,:10,:])             # let's print a small slice of E

[[2.1227920e-13 5.9975574e-43 5.4333205e-11]
 [5.9975574e-43 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]]


So, `E` is essentially initialized with random values. Other options include:

In [19]:
E = np.random.random(shp)  # array containing random values in [0,1)
print(E[0,:3,:])
print('\n')
E = np.zeros(shp, dtype='f')  # array containing zeros
print(E[0,:3,:])
print('\n')
E = np.ones(shp, dtype='f')  # array containing ones
print(E[0,:3,:])
print('\n')
E = np.full(shp, 7, dtype='f')  # array containing sevens
print(E[0,:3,:])
print('\n')
E = np.arange(np.prod(shp), dtype='f').reshape(shp)  # array with values from range(size)
# The above line consists of three commands:
# the first one, np.prod(shp), returns the product of the values in shp, i.e. 3*2*3 = 18.
# the second one, np.arrange(18), creates a 1D array containing elements from range(18), i.e. C = [0, 1, 2, ... 17].
# the last one, E.reshape(shp), changes E's shape to shp.
print(E[0,:3,:])

[[0.65064177 0.95017194 0.45061587]
 [0.70643226 0.30573079 0.84369375]
 [0.1148261  0.67839778 0.23793187]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Once we have an array of the shape and dtype of our choice, we can populate it with the values that we want.

In [20]:
import math

for i in range(E.shape[0]):
    for j in range(E.shape[1]):
        for k in range(E.shape[2]):
            E[i,j,k] = math.sin(i*math.pi)
            
print(E[:10, 1, 2])

[ 0.0000000e+00  1.2246469e-16 -2.4492937e-16  3.6739403e-16
 -4.8985874e-16  6.1232340e-16 -7.3478806e-16  8.5725277e-16
 -9.7971748e-16  1.1021821e-15]


### Array operations

By default, most operations performed on numpy arrays are elementwise.

$$
Arr1 = \left( \begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \end{array} \right), \:
Arr2 = \left( \begin{array}{ccc}
11 & 12 & 13 \\
14 & 15 & 16 \\
17 & 18 & 19 \end{array} \right)
$$

For example in numpy the product of these two arrays is:

$$
Arr1 \cdot Arr2 =
\left( \begin{array}{ccc}
11 & 24 & 39 \\
56 & 75 & 96 \\
119 & 144 & 171 \end{array} \right)
$$

#### Elementwise operations

In [21]:
print('A =               ', A)
print('A + 1 =           ', A + 1)
print('A ** 2 =          ', A ** 2)
O = np.arange((3))
print('O =               ', O)
print('A + O =           ', A + O)
print('A * O =           ', A * O)
print('2 ** (O + 1) - A =', 2 ** (O + 1) - A)

A =                [2 5 7]
A + 1 =            [3 6 8]
A ** 2 =           [ 4 25 49]
O =                [0 1 2]
A + O =            [2 6 9]
A * O =            [ 0  5 14]
2 ** (O + 1) - A = [ 0 -1  1]


These are also equivalent to.

```python
np.add(A, O)
np.subtract(A, O)
np.multiply(A, O)
np.divide(A, O)
np.exp(A)
np.sqrt(A)
```

Note that `A * O` is **not** matrix multiplication! It is an **elementwise multiplication**.

#### Vecotr/Matrix operations

In [22]:
print('matrix mul: A * O = ', np.dot(A, O))
print('same as: ', A.dot(O))
print('outer product: A x O\n', np.outer(A,O))

matrix mul: A * O =  19
same as:  19
outer product: A x O
 [[ 0  2  4]
 [ 0  5 10]
 [ 0  7 14]]


#### Broadcasting

Some elementwise operations are not defined mathematically. For this reason, numpy uses a technique called broadcasting. What this does is it repeats the element that has less axes to match the other. This is illustrated in the image below.

![](http://www.scipy-lectures.org/_images/numpy_broadcasting.png)

Note, the dimensions must be compatible for broadcasting to work (the dimension being repeated needs to be divisible by the dimension it is going to match.

```python
x  # array with shape (6, 2)
y  # array with shape (6, 3)
z  # array with shape (6, 8)

x + y  # error
y + z  # error
x + z  # array with shape (6, 8)
```

### Exercise 1: Try to confirm the above image in numpy

### Solution:

In [23]:
A = np.array([[0], [10], [20], [30]]).repeat(3, axis=1)
# Creates a column array with 4 values and repeats 3 times it along the horizontal axis.
B = np.array([[0, 1, 2],]).repeat(4, axis=0)
# Creates an array with 3 values and repeats 4 times it along the vertical axis.
print('{} \n + \n {} \n = \n {}'.format(A, B, A+B))

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 
 + 
 [[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] 
 = 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [24]:
B = np.array([0, 1, 2])
print('{} \n + \n {} \n = \n {}'.format(A, B, A+B))      

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 
 + 
 [0 1 2] 
 = 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [25]:
A = np.array([[0], [10], [20], [30]])
print('{} \n + \n {} \n = \n {}'.format(A, B, A+B))      

[[ 0]
 [10]
 [20]
 [30]] 
 + 
 [0 1 2] 
 = 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


#### Logical Operations

An array can also contain boolean values in it. Logical operations are operations between two such arrays.

In [26]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True False]
[ True False False False]


We can also compare the two arrays with all known logical operators. Like all `numpy` operators, they perform their operations elementwise.

In [27]:
print(a > b)  # True if the element of a is larger than the corresponding element of b 
print(a == b)
print(a != b)

[False  True False False]
[ True False False  True]
[False  True  True False]


**Tip:** You can use `np.all()` or `np.any()` for comparing arrays as a whole (python's built-in `all()`, `any()` functions may not work properly with arrays).

#### Transcendental Functions

These compute the `math` package functions to all the elements of an array.

In [28]:
a = np.arange(-1, 4)

print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[-0.84147098  0.          0.84147098  0.90929743  0.14112001]
[       nan       -inf 0.         0.69314718 1.09861229]
[ 0.36787944  1.          2.71828183  7.3890561  20.08553692]


c:\users\thano\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
c:\users\thano\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.


One interesting thing to note is how numpy handles non existing values. In the previous example we introduced two operations that are normally not defined in computational software ($log(-1) = nan, \; log(0) = -\infty$). Numpy throws a runtime warning (**not an error**) each time it encounters such an operation and performs all operation it can. Numpy can also differentiate between operations yielding `nan` (i.e. *not a number*) and infinite.

We can ignore the warnings if we wish to perform such operations and we are aware of their outcome, though this is **not suggested**.

In [29]:
import warnings
warnings.filterwarnings("ignore")

print(np.log(-1))
print(type(np.log(-1)))
print(np.log(0))
print(type(np.log(0)))

nan
<class 'numpy.float64'>
-inf
<class 'numpy.float64'>


The existance of `nan` values might create a probems during operations.

In [38]:
nan_array = np.array([1, 2, np.nan, 4, 5])
nan_array.sum()

nan

Here, numpy won't perform the summation because one of its values is `nan`. Numpy offers a series of functions that simply ignore `nan` values. 

In [39]:
np.nansum(nan_array)

12.0

### Filtering

Logical operations provide a convenient way to *filter* arrays. 

Performing such an operation returns an array with the same shape as the original that just contains `True` and `False` values.

In [33]:
condition = C % 2 == 0  # condition checks if an element is even or not
condition

array([[[ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False]]])

By indexing the original array by the result of the logical operation, numpy will the elements of the original that correspond to `True` values. This is also known as **boolean indexing**.

In [35]:
C[condition]  # filters out the elements with False values (i.e. the odd ones)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

### Array concatenation

Another important operation is concatenating (or merging numpy arrays). Suppose we have the following two arrays:

$$
Arr1 = \left( \begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \end{array} \right), \:
Arr2 = \left( \begin{array}{ccc}
11 & 12 & 13 \\
14 & 15 & 16 \\
17 & 18 & 19 \end{array} \right)
$$

These arrays are 3-dimensional, so there are three ways of joining them:

- along the first axis (i.e. the rows):

$$
concat1 = \left( \begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
11 & 12 & 13 \\
14 & 15 & 16 \\
17 & 18 & 19 \end{array} \right)
$$

For this concatenation to work, the arrays should have the same number of columns.

- along the second axis (i.e. the columns):

$$
concat2 = \left( \begin{array}{ccc}
1 & 2 & 3 & 11 & 12 & 13\\
4 & 5 & 6 & 14 & 15 & 16\\
7 & 8 & 9 & 17 & 18 & 19\\ \end{array} \right)
$$

For this concatenation to work, the arrays should have the same number of rows.

- along a new axis:

This would yield a 3-dimensional array. The first two dimensions should have the same shape as the first two dimensions of the arrays we want to concatenate. The arrays should have the same number of rows and columns. The third dimension will differentiate between the input arrays.

In [30]:
Arr1 = np.arange(1,10).reshape((3,3))
Arr2 = np.arange(11,20).reshape((3,3))

print('Along first axis:')
concat1 = np.concatenate([Arr1, Arr2], axis=0)
print(concat1)
print(concat1.shape)

concat1 = np.vstack([Arr1, Arr2])  # alternative (vertical stack)
print(concat1.shape)

print('\nAlong second axis:')
concat2 = np.concatenate([Arr1, Arr2], axis=1)
print(concat2)
print(concat2.shape)

concat1 = np.hstack([Arr1, Arr2])  # alternative (horizontal stack)
print(concat2.shape)

print('\nAlong new axis:')
concat3 = np.stack([Arr1, Arr2], axis=2)
# Stack will always concatenate the arrays on a new axis. The argument allow us to select where to place that axis.
print(concat3)
print(concat3.shape)

Along first axis:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
(6, 3)
(6, 3)

Along second axis:
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
(3, 6)
(3, 6)

Along new axis:
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]]
(3, 3, 2)


### Matrices

Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations.

Generally, it is preferable to use arrays instead of matrices. The only advantage matrices have, is that operators such as \* and \*\* are used for matrix multiplication and matrix power.

However, it is almost always recommended to use arrays instead of matrices! 

In [31]:
mat1 = np.matrix('1 2; 3 4')  # matrices can be created with a matlab-like syntax
mat2 = np.matrix([[10, 20], [30, 40]])

print(mat1 * mat2)  # matrix multiplication

[[ 70 100]
 [150 220]]


### Input/Output operations

The easiest way of saving/loading numpy arrays is through the built-in functions `np.save` and `np.load`. The default format is a binary NumPy `.npy` format using python pickles.

In [32]:
np.save('my_array.npy', B)  # store array B into a file named 'my_array.npy'
B_loaded = np.load('my_array.npy')  # loads array 'my_array.npy' into variable B_loaded
print(B_loaded)
print('original data type:', B.dtype, '\nloaded data type:', B_loaded.dtype)

[0 1 2]
original data type: int32 
loaded data type: int32


#### CSV

While binary `.npy` files might be more memory efficient and faster for saving/loading, they have two major drawbacks. They can't be read by other programs (matlab, R, etc.) and they aren't **human readable**. The most common way of storing data in arrays in the so-called CSV format. CSV stands for *comma-separated values*. This means we store the array in a text file. The values in the columns are separated with *commas*, while rows are separated with *new lines*. 

For example:
$$ B = \left( \begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \end{array} \right) $$
Is stored as:
```
1,2,3
4,5,6
```
To store arrays as csv files we can use `np.savetxt` and `np.loadtxt`.

In [33]:
np.savetxt('my_array.csv', B, delimiter=',')  # default delimiter is a single space
B_loaded = np.loadtxt('my_array.csv', delimiter=',')  # since we didn't use de default delimiter we must specify it when loading
print(B_loaded)
print('original data type:', B.dtype, '\nloaded data type:', B_loaded.dtype)

[0. 1. 2.]
original data type: int32 
loaded data type: float64


Note that CSVs don't store any extra information about the array other than its values. This is why when we stored and loaded the array the data type changed to the numpy's default `float64`. On the other hand, when saving as a binary file, this extra information is preserved.

Generally speaking, binary formats are more efficient (faster i/o, less memory) but text formats are more universal (e.g. can be loaded into any program).

## SciPy

> SciPy is a python library used for high-level scientific computations. Many scipy functions are built on top of numpy.

### Input/Output Operations - compatibility with matlab

Saving and loading matlab files:
```python
A = np.matrix(...)
B = np.matrix(...)
scipy.io.savemat('name.mat', {'A': A})  # saves matlab files
scipy.io.savemat('name.mat', {'B': B})  # expects a dictionary
data = scipy.io.loadmat('name', struct_as_record=True)
A = data['A']
B = data['B']
```

### Linear Algebra Operations

In [34]:
A = np.array([[1, 2], [3, 4]])

from scipy import linalg
print('Determinant:', linalg.det(A))
# returns the determinant of a square matrix

print('Inverse: \n', linalg.inv(A))
# returns the inverse of a matrix

w, v = linalg.eig(A)
# eigenvalues and eigenvectors

U, S, V = linalg.svd(A)
# singular value decomposition

Determinant: -2.0
Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Sparse Matrices

When having sparse data, there is a huge waste of space if we use numpy matrices.

Why? Let's see an example.

In [35]:
S = np.zeros((10000, 10000), dtype='float64')
# We first create a matrix of zeros
S[1234, 5678] = 0.34556678
S[6547, 7458] = 0.87584656
S[2846, 6944] = 0.87454111
S[3741, 1244] = 0.78654588
# Then we enter 4 values we wanted
print(S.nbytes)

800000000


We're using up 800,000,000 bytes of memory, or 762MB just to store 4 numbers! Why is this?

NumPy consumes: `(10000 x 10000) elements x 64 bits / 8 bits-per-byte = 762MB ` of memory for the array regardless of whether or not they actually contain values or not!

What if we had a matrix with a size of `(100000 x 100000)` ? This is where we require sparse matrices. Sparse matrices store just a list of the elements that aren't empty. There are a few different sparse matrix formats, each with its pros and cons. Most common are:

- **List of Lists** (LIL). Stores two lists: One containing lists of the column indices for each row and one containing lists of their corresponding values. Efficient modification of single elements but slow arithmetic operations.
- **Coordinate Format** (COO). Stores a list of (row, column, value) tuples. Fast to add new elements, but slow at everything else.
- **Compressed Sparse Row Format** (CSR). This format is sorted by rows. Allows for fast csr+csr or csr\*csr operations and really fast row slicing. Not good for element or structure modification.
- **Compressed Sparse Column Format** (CSC). This format is sorted by columns. Allows for fast csc+csc or csc\*csc operations and really fast column slicing. Not good for element or structure modification.
- **Block Compressed Row** (BCR). This format is similar to the CSR format. It helps create dense blocks in a greater sparse matrix. BSR is appropriate for sparse matrices with dense sub matrices.

### Other operations

SciPy is a huge package with many subpackages. We won't look at them in much detail.

- `scipy.special`  
    Special functions are transcendental functions. Contains implementations of the Bessel, Elliptic, Gamma and Error functions.

- `scipy.optimization`  
    Optimization is the problem of finding a numerical solution to a minimization or equality.

- `scipy.ffrpack`  
    Submodule for computing Fast Fourier Transforms.
    
- `scipy.optimize`  
    Optimization is the problem of finding a numerical solution to a minimization or equality. 

- `scipy.stats`  
    The module contains statistical tools and probabilistic descriptions of random processes. There is also a built-in python `statistics` module for statistical computations.

- `scipy.interpolate`  
    Interpolation is used for fitting a function from experimental data and thus evaluating points where no measure exists.
    
- `scipy.integrate`  
    Submodule used for integration and Ordinary Differential Equations.

- `scipy.signal`  
    Submodule used for signal processing.

- `scipy.ndimage`  
    This submodule is used for image processing.
    
## Tips

### Automatic Reshaping

In [45]:
A = np.arange(30)
A.shape = 2, -1, 3 # -1 means 'whatever is needed'
print(A)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [47]:
A = A.reshape(-1, 10)
print(A.shape)
A = A.reshape(3, 5, -1)
print(A.shape)
A = A.reshape(-1, 1)
print(A.shape)
A = A.reshape(1, -1)
print(A.shape)

(3, 10)
(3, 5, 2)
(30, 1)
(1, 30)


### Unique values

In [48]:
A = np.array([1] * 101 + [2] * 3 + [5] * 75 + [9] * 21)

Use `np.unique()` to find the unique values of an array.

In [49]:
np.unique(A)

array([1, 2, 5, 9])

Add the argument `return_counts=True` to return a second array containing the number of occurrences for each of the unique values. 

In [51]:
unique, counts = np.unique(A, return_counts=True)
print(unique)
print(counts)

[1 2 5 9]
[101   3  75  21]


### Random

NumPy has excellent support for random numbers.

**Regular functions:**
- np.random.rand(shp) returns random values in a given shape.
- np.random.random() returns random floats in [0,1).
- np.random.shuffle(x) shuffles the contents of x. 

**Distributions:**
- np.random.binomial(n,p)
- np.random.gamma(shp)
- np.random.geometric(p)
- np.random.multinomial(n,p)
- np.random.poisson()

### Exercise 2

Find the unique numbers in a given numpy array and calculate their frequencies.

In [37]:
data = np.concatenate([np.random.randint(2, size=300),
                       np.random.randint(3, size=400),
                       np.random.randint(4, size=400)])

### Solution

In [38]:
values, frequencies = np.unique(data, return_counts=True)
frequencies = frequencies / frequencies.sum() * 100
for z in zip(values, frequencies):
    print('Value {}: Frequency: {:.2f}%'.format(z[0], z[1]))

Value 0: Frequency: 34.55%
Value 1: Frequency: 35.91%
Value 2: Frequency: 21.18%
Value 3: Frequency: 8.36%


### Exercise 3

Given a numpy array, identify the missing values and replace them with the mean of each value's column.

In [39]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
data[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

### Solution 1 (explanatory)

In [40]:
# check if there are any nan values in the array
print(np.any(np.isnan(data)))

# first find the mean of each column of the array:
means = np.nanmean(data, axis=0)  # we must use np.nanmean because of the nan values in the array

# identify nan values in the array:
rows, cols = np.where(np.isnan(data))
# np.isnan runs an elementwise check if each value is nan
# np.where returns their locations in two separate arrays one for first axis indexes and one for the second

# replace each nan element with the correct mean value:
for i in range(len(rows)):  # iterate over the number of nan values in the array
    data[rows[i], cols[i]] = means[cols[i]]  # replace each nan value with the mean value of its column
    
print(np.any(np.isnan(data)))

True
False


### Solution 2 (pythonic)

In [41]:
print(np.any(np.isnan(data)))
data[np.isnan(data)] = np.nanmean(data[:, np.where(np.isnan(data))[1]], axis=0)
print(np.any(np.isnan(data)))

False
False
